package l2s.gameserver.network.l2.s2c.custom;

/**
 * @author Bonux (bonuxq@gmail.com)
 * @date 04.01.2024
 **/
public enum SExCustomOpcode {
	/*0*/S_EX_C_MONSTER_DROP_LIST,
	/*1*/S_EX_C_ITEMS_TO_ENCHANT_LIST,
	/*2*/S_EX_C_ITEMS_TO_ENCHANT_LIST_MULTI,
	/*3*/S_EX_C_COLLECTION_FEE_LIST,
	/*4*/S_EX_C_COSTUME_LIST,
	/*5*/S_EX_C_COSTUME_ACTIVATE,
	/*6*/S_EX_C_COSTUME_ACTION_RESULT,
	/*7*/S_EX_C_COLLECTION_PURCHASE_LIST,
	/*8*/S_EX_C_PREDEFINED_CHANCES_ITEM_JEWEL,
	/*9*/S_EX_C_PREDEFINED_CHANCES_ITEM_ENCHANT,
	/*10*/S_EX_C_ITEM_ENCHANT_LIMIT,
	/*11*/S_EX_C_ITEM_JEWEL_ENCHANT_LIMIT,
	/*12*/S_EX_C_CUSTOM_COMBINATION_CHANCE,
	/*13*/S_EX_C_ITEMS_TO_COMMISSION_LIST,
	/*14*/S_EX_C_TARGET_STATUS,
    /*15*/S_EX_C_AUTO_RANDOM_CRAFT_INFO,
	/*16*/S_EX_C_GFX_ANNOUNCE;
}
